name = "picksbothook"
main = "workers/telegram_bot.js"
compatibility_date = "2024-12-01"

[vars]
TELEGRAM_API = "https://api.telegram.org"

# Rutas: ajusta si quieres dominio propio
routes = []

[observability]
enabled = true
