name: Daily Run (America/Merida 02:30)

on:
  schedule:
    - cron: "30 8 * * *"  # 08:30 UTC = 02:30 America/Merida
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env
        run: |
          echo "Cargando variables de entorno"
        env:
          ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
          FOOTBALLDATA_KEY: ${{ secrets.FOOTBALLDATA_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Run daily pipeline
        run: |
          python scripts/run_daily.py
        env:
          ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
          FOOTBALLDATA_KEY: ${{ secrets.FOOTBALLDATA_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
