cat > .github/workflows/daily_ingest.yml <<'YML'
name: Daily Ingest

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 UTC (ajusta si quieres)
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run ingest daily
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GOOGLE_SHEETS_CREDENTIALS_JSON_B64: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_JSON_B64 }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
        run: |
          python scripts/ingest_daily.py
YML
