name: Weekly Backfill (Tuesday 02:00 America/Merida)

on:
  schedule:
    - cron: "0 8 * * 2"  # 08:00 UTC = 02:00 America/Merida (martes)
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Env
        run: |
          echo "Cargando variables de entorno"
        env:
          ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
          FOOTBALLDATA_KEY: ${{ secrets.FOOTBALLDATA_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Backfill 3 años (all)
        run: |
          python scripts/backfill_historical.py --sport all --years 3
        env:
          ODDSAPI_KEY: ${{ secrets.ODDSAPI_KEY }}
          FOOTBALLDATA_KEY: ${{ secrets.FOOTBALLDATA_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
