name: Daily Pipeline
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch: {}
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Ingest
        run: python -m src.pipelines.ingest
      - name: Train
        run: python -m src.pipelines.train_baseline
      - name: Publish to Sheets
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          DEFAULT_BANKROLL: ${{ vars.DEFAULT_BANKROLL }}
          DEFAULT_KELLY_FRACTION: ${{ vars.DEFAULT_KELLY_FRACTION }}
          DEFAULT_TOP_PICKS: ${{ vars.DEFAULT_TOP_PICKS }}
          GSHEET_PICKS_TAB: ${{ vars.GSHEET_PICKS_TAB }}
        run: python -m src.pipelines.predict_and_publish
