name: Fix Exec Bit (One-off)
on: workflow_dispatch

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make file executable
        run: |
          chmod +x make_all.sh

      - name: Commit back
        uses: EndBug/add-and-commit@v9
        with:
          add: "make_all.sh"
          message: "chore: set +x on make_all.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
